js-application-analytics - Updated to SPFX 1.20
pnp/sp-dev-fx-extensions pull request #1442
Opened 2024-10-21 20:47 UTC by NicolasKheirallah

> By submitting this pull request, you agree to the [contribution guidelines](https://github.com/pnp/sp-dev-fx-extensions/blob/main/CONTRIBUTING.md)

> If you aren't familiar with how to contribute to open-source repositories using GitHub, or if you find the instructions on this page confusing, [sign up](https://forms.office.com/Pages/ResponsePage.aspx?id=KtIy2vgLW0SOgZbwvQuRaXDXyCl9DkBHq4A2OG7uLpdUREZVRDVYUUJLT1VNRDM4SjhGMlpUNzBORy4u) for one of our [Sharing is Caring](https://pnp.github.io/sharing-is-caring/#pnp-sic-events) events. It's completely free, and we'll guide you through the process.

|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| Bug fix?        | no                              |
| New feature?    | no                               |
| New sample?     | no                             |
| Related issues? | Updated to SPFX 1.20 and updated rest of modules etc. |

## What's in this Pull Request?

> Please describe the changes in this PR. Sample description or details around bugs which are being fixed.
Updated to SPFX 1.20 and updated rest of modules  etc

2024-10-22 21:45 UTC, Adam-it requested changes
@NicolasKheirallah Awesome work so far 👏👏👏
I didn't manage to `gulp bundle` the solution. Lets double check if it build before we merge
![image](https://github.com/user-attachments/assets/29918b79-d320-4486-989a-e7a26174eb93)

Also besides the files you already change we should also update the `assets/sample.json` and there we should update the `updateDateTime` and `SPFX-VERSION` metadata to 1.20.0.

Also did you generate the upgrade guidance for this project and go over all the required changes? I did that and a few recommended and required things that still should be done before we proceed 
![image](https://github.com/user-attachments/assets/404a20ae-5647-4c91-aa50-28d17a35fc9e)

2024-10-22 21:45 UTC, Adam-it commented on samples/js-application-analytics/README.md
in this file in the `Compatibility` section you should also update to tags to SPFx 1.20 and Node to v18

2024-10-22 21:45 UTC, Adam-it commented on samples/js-application-analytics/package.json
> +    "@microsoft/rush-stack-compiler-4.5": "^0.5.1",
seems we have two versions of rush-stack now. 
only the second one should stay

2024-10-22 21:45 UTC, Adam-it commented on samples/js-application-analytics/src/extensions/analytics/AnalyticsApplicationCustomizer.tsx
don't we have the same in `.ts` file? why we duplicate the logic?

2024-10-23 22:29 UTC, NicolasKheirallah commented on samples/js-application-analytics/src/extensions/analytics/AnalyticsApplicationCustomizer.tsx
Thanks for the feedback! Learning alot! :) 
Yeah, It was suppose only to have a .TS file
All suggested issues should be fixed now! :)

2024-10-29 07:25 UTC, Adam-it commented on samples/js-application-analytics/README.md
@NicolasKheirallah I think you still missed to update the tags in the readme file. Could you have a recheck?

2024-10-29 09:33 UTC, NicolasKheirallah commented on samples/js-application-analytics/README.md
You are 100% correct! Tags have now been updated! :)
![image](https://github.com/user-attachments/assets/3b3da22e-928a-49d1-89c7-ba7f8ae22df1)

2024-10-29 20:54 UTC, Adam-it approved these changes
@NicolasKheirallah awesome work 👏👏👏
LGTM 👍

2024-10-29 20:57 UTC, merged